### ISSUE TITLE
Inquiry About API Usage Costs for Large Language Models

### ISSUE THREAD

**Issue by itsLee1218** [FanGShiYuu/CoDrivingLLM#5]
Thanks for your excellent work！I find it incredibly insightful and valuable for my own research. 
I have a question regarding the usage of large language models in the project. Could you kindly provide an estimate of the costs associated with running the API for these models?
Thank you in advance for your time and assistance. I truly appreciate your help.

**Comment by FanGShiYuu** [comment]
Thank you for your kind words! Regarding the pricing of different models, you can refer to [OpenAI's pricing page](https://openai.com/api/pricing/).  

In our code, we have defaulted to the more economical `4o-mini` model because our primary contribution is not improving the model itself but leveraging LLMs to achieve vehicle-to-vehicle collaboration.  

Additionally, you can calculate your input tokens using [OpenAI's tokenizer tool](https://platform.openai.com/tokenizer).  

Thank you again for your attention to our work! We hope our response is helpful. 😊
